module 3 task 1 done
htmlacademy-javascript/1484665-code-and-magick-21 pull request #3
Opened 2020-09-27 09:07 UTC by Gekol

2020-09-28 08:59 UTC, sterlikoff requested changes
Георгий, в целом хорошо, но есть некоторые замечания:

1. Особого смысла выносить в переменную setupBlock нет, ведь она больше нигде не используется. Можно заменить на более лаконичный вид: showBlock(document.querySelector(`.setup`));

А еще лучше сделать аргументом функции showBlock не сам блок, а селектор, а document.querySelector выполнять уже там. То есть showBlock(`.setup`);

В функции обязательно проверить нашелся ли блок по селектору, чтобы не отхватить исключение.

То же и для setupSimilarBlock.

2. Немного поломал голову над реализацией generateRandomInt :) Во многих языках программирования и библиотеках сначала min, а потом max. Не критично, но желательно поправить.

3. Генерацию имени персонажа - в функцию!

   let newCharacter = {
      name: generateName(), // @todo вынести в функцию
      coatColor: COAT_COLORS[generateRandomInt(COAT_COLORS.length)],
      eyesColor: EYES_COLORS[generateRandomInt(EYES_COLORS.length)]
    };


4. Убрать wizardTemplate и wizardsList из глобальной части кода туда, где они по факту используются. Глобально объявляем большими буквами только статичные (не вычисляемые) значения, используемые в нескольких местах программы. 

5. Время от времени попадаются имена вида "Верон undefined". Нужно помнить, что элементы в массиве от 0 до (Длина_Массива - 1).

Поправь эти места и будет отлично! :)

2020-09-28 11:08 UTC, Gekol commented
@sterlikoff Даниил, может мне wizardsList объявить через let? Саму переменную я не переопределяю, но переопределяю поля объекта, на который переменная указывает. Не значит ли это, что переменная чисто логически не константа?

2020-09-28 17:25 UTC, sterlikoff requested changes
Георгий, давай доработаем еще кое что:

1. Не забываем про тернарный оператор

Вместо большого куска

  let fullName = ``;
  if (nameFirstPositionProbability > 50) {
    fullName = `${name} ${surname}`;
  } else {
    fullName = `${surname} ${name}`;
  }
  return fullName;

можно написать одну строку

return nameFirstPositionProbability > 50 ? `${name} ${surname}` : `${surname} ${name}`;

Вообще штука непонятная, почему рандом из 100 и сравнение с 50. Можно ведь и обойтись нулем и единицей, к примеру :)

2. Ненужная переменная newCharacter, сразу добавляем объект в массив.
3. Для массива там же лучше все же push:     

    characters.push({
      name: generateCharacterName(),
      coatColor: COAT_COLORS[generateRandomInt(0, COAT_COLORS.length - 1)],
      eyesColor: EYES_COLORS[generateRandomInt(0, EYES_COLORS.length - 1)]
    });

4. Не очень понятно, зачем нужно const fragment = document.createDocumentFragment();

можно ведь сразу в wizardsList класть. и wizardsList - const.

2020-09-28 17:28 UTC, sterlikoff commented
> @sterlikoff Даниил, может мне wizardsList объявить через let? Саму переменную я не переопределяю, но переопределяю поля объекта, на который переменная указывает. Не значит ли это, что переменная чисто логически не константа?

Нет, в wizardsList хранится лишь своебразная "ссылка" на элемент. Эта ссылка не изменяется если делаешь appendChild в этот элемент, поэтому все же wizardsList - константа.

2020-09-29 03:42 UTC, Gekol commented
> Георгий, давай доработаем еще кое что:
> 
> 1. Не забываем про тернарный оператор
> 
> Вместо большого куска
> 
> let fullName = ``;
> if (nameFirstPositionProbability > 50) {
> fullName = `${name} ${surname}`;
> } else {
> fullName = `${surname} ${name}`;
> }
> return fullName;
> 
> можно написать одну строку
> 
> return nameFirstPositionProbability > 50 ? `${name} ${surname}` : `${surname} ${name}`;
> 
> Вообще штука непонятная, почему рандом из 100 и сравнение с 50. Можно ведь и обойтись нулем и единицей, к примеру :)
> 
> 1. Ненужная переменная newCharacter, сразу добавляем объект в массив.
> 2. Для массива там же лучше все же push:
>    characters.push({
>    name: generateCharacterName(),
>    coatColor: COAT_COLORS[generateRandomInt(0, COAT_COLORS.length - 1)],
>    eyesColor: EYES_COLORS[generateRandomInt(0, EYES_COLORS.length - 1)]
>    });
> 3. Не очень понятно, зачем нужно const fragment = document.createDocumentFragment();
> 
> можно ведь сразу в wizardsList класть. и wizardsList - const.

В Интернете было сказано, что если использовать Document.fragment, то добавлять в него дочерние элементы будет быстрее, так как фрагмент хранится в памяти и добавление не будет вызывать перестройку страницы. А когда я добавлю весь фрагмент в wizardsList, страница перестроится всего 1 раз. Или это все как-то иначе работает?

2020-09-29 16:58 UTC, sterlikoff approved these changes
Теперь отлично. Зачет!

2020-09-29 16:58 UTC, merged